[project]
name = "price-checker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "opencv-python-headless>=4.12.0.88",
    "openfoodfacts>=2.8.0",
    "pyzbar>=0.1.9",
]
